spring:
  data:
    jdbc:
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student_code
    username: postgres
    password: postgres
  jpa:
